2022-10-11 04:21:02,751 INFO    Thread-7  :27295 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 04:21:02,751 INFO    Thread-7  :27295 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 04:21:02,751 INFO    Thread-7  :27295 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'run_id': 'p7seo4g7', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-insiafob/config-p7seo4g7.yaml', 'sweep_id': 'insiafob'}
2022-10-11 04:21:02,751 INFO    Thread-7  :27295 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 04:21:02,751 INFO    Thread-7  :27295 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_042102-p7seo4g7/logs/debug.log
2022-10-11 04:21:02,751 INFO    Thread-7  :27295 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_042102-p7seo4g7/logs/debug-internal.log
2022-10-11 04:21:02,752 INFO    Thread-7  :27295 [wandb_init.py:init():439] calling init triggers
2022-10-11 04:21:02,752 INFO    Thread-7  :27295 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 40, 'dropout': 0.5, 'epochs': 1, 'fc_layer_size': 128, 'learning_rate': 0.05349027503791061, 'optimizer': 'sgd'}
config: {}
2022-10-11 04:21:02,752 INFO    Thread-7  :27295 [wandb_init.py:init():492] starting backend
2022-10-11 04:21:02,752 INFO    Thread-7  :27295 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 04:21:02,756 INFO    Thread-7  :27295 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 04:21:02,766 INFO    Thread-7  :27295 [backend.py:ensure_launched():225] started backend process with pid: 27427
2022-10-11 04:21:02,768 INFO    Thread-7  :27295 [wandb_init.py:init():501] backend started and connected
2022-10-11 04:21:02,775 INFO    Thread-7  :27295 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 40, 'dropout': 0.5, 'epochs': 1, 'fc_layer_size': 128, 'learning_rate': 0.05349027503791061, 'optimizer': 'sgd'}
2022-10-11 04:21:02,777 INFO    Thread-7  :27295 [wandb_init.py:init():565] updated telemetry
2022-10-11 04:21:02,799 INFO    Thread-7  :27295 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 04:21:03,769 INFO    Thread-7  :27295 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 04:21:03,878 INFO    Thread-7  :27295 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 04:21:03,879 INFO    Thread-7  :27295 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 04:21:06,695 INFO    Thread-7  :27295 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 04:21:06,696 INFO    Thread-7  :27295 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 04:21:06,696 INFO    Thread-7  :27295 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 04:21:06,696 ERROR   Thread-7  :27295 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 04:21:06,696 INFO    Thread-7  :27295 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 04:21:06,697 INFO    Thread-7  :27295 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/p7seo4g7
2022-10-11 04:21:06,697 INFO    Thread-7  :27295 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 04:21:06,699 INFO    Thread-7  :27295 [wandb_run.py:_restore():1674] restore
2022-10-11 04:21:06,833 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 699
}

2022-10-11 04:21:07,034 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 04:21:07,860 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 9455
}

2022-10-11 04:21:07,962 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 9455
}

2022-10-11 04:21:08,064 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:08,166 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:08,269 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:08,373 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:08,475 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:08,577 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:08,776 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:09,127 INFO    Thread-7  :27295 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}
local_info {
}

2022-10-11 04:21:10,702 INFO    Thread-7  :27295 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-10-11 04:21:10,702 INFO    Thread-7  :27295 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-10-11 04:21:10,704 INFO    Thread-7  :27295 [wandb_run.py:_footer_sync_info():2822] logging synced files
