2022-10-11 04:20:52,383 INFO    Thread-2  :27295 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 04:20:52,383 INFO    Thread-2  :27295 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 04:20:52,383 INFO    Thread-2  :27295 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'sweep_id': 'insiafob', 'run_id': 'a59nixtq', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-insiafob/config-a59nixtq.yaml'}
2022-10-11 04:20:52,383 INFO    Thread-2  :27295 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 04:20:52,383 INFO    Thread-2  :27295 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_042052-a59nixtq/logs/debug.log
2022-10-11 04:20:52,384 INFO    Thread-2  :27295 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_042052-a59nixtq/logs/debug-internal.log
2022-10-11 04:20:52,384 INFO    Thread-2  :27295 [wandb_init.py:init():439] calling init triggers
2022-10-11 04:20:52,384 INFO    Thread-2  :27295 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 64, 'dropout': 0.5, 'epochs': 1, 'fc_layer_size': 256, 'learning_rate': 0.01537201008451723, 'optimizer': 'adam'}
config: {}
2022-10-11 04:20:52,384 INFO    Thread-2  :27295 [wandb_init.py:init():492] starting backend
2022-10-11 04:20:52,384 INFO    Thread-2  :27295 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 04:20:52,399 INFO    Thread-2  :27295 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 04:20:52,410 INFO    Thread-2  :27295 [backend.py:ensure_launched():225] started backend process with pid: 27328
2022-10-11 04:20:52,412 INFO    Thread-2  :27295 [wandb_init.py:init():501] backend started and connected
2022-10-11 04:20:52,420 INFO    Thread-2  :27295 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 64, 'dropout': 0.5, 'epochs': 1, 'fc_layer_size': 256, 'learning_rate': 0.01537201008451723, 'optimizer': 'adam'}
2022-10-11 04:20:52,422 INFO    Thread-2  :27295 [wandb_init.py:init():565] updated telemetry
2022-10-11 04:20:52,451 INFO    Thread-2  :27295 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 04:20:53,420 INFO    Thread-2  :27295 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 04:20:53,470 INFO    Thread-2  :27295 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 04:20:53,470 INFO    Thread-2  :27295 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 04:20:56,195 INFO    Thread-2  :27295 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 04:20:56,196 INFO    Thread-2  :27295 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 04:20:56,196 INFO    Thread-2  :27295 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 04:20:56,204 ERROR   Thread-2  :27295 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 04:20:56,207 INFO    Thread-2  :27295 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 04:20:56,207 INFO    Thread-2  :27295 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/a59nixtq
2022-10-11 04:20:56,207 INFO    Thread-2  :27295 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 04:20:56,210 INFO    Thread-2  :27295 [wandb_run.py:_restore():1674] restore
2022-10-11 04:20:56,330 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 699
}

2022-10-11 04:20:56,516 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 04:20:57,430 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 04:20:57,533 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 9456
}

2022-10-11 04:20:57,635 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 8754
  total_bytes: 9456
}

2022-10-11 04:20:57,738 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9456
  total_bytes: 9456
}

2022-10-11 04:20:57,840 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9456
  total_bytes: 9456
}

2022-10-11 04:20:57,942 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9456
  total_bytes: 9456
}

2022-10-11 04:20:58,044 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9456
  total_bytes: 9456
}

2022-10-11 04:20:58,145 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9456
  total_bytes: 9456
}

2022-10-11 04:20:58,334 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9456
  total_bytes: 9456
}

2022-10-11 04:20:58,704 INFO    Thread-2  :27295 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9456
  total_bytes: 9456
}
local_info {
}

2022-10-11 04:21:00,269 INFO    Thread-2  :27295 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-10-11 04:21:00,269 INFO    Thread-2  :27295 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-10-11 04:21:00,271 INFO    Thread-2  :27295 [wandb_run.py:_footer_sync_info():2822] logging synced files
