2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'run_id': 'k4n9z3o0', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-insiafob/config-k4n9z3o0.yaml', 'sweep_id': 'insiafob'}
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_042113-k4n9z3o0/logs/debug.log
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_042113-k4n9z3o0/logs/debug-internal.log
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_init.py:init():439] calling init triggers
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 64, 'dropout': 0.5, 'epochs': 1, 'fc_layer_size': 512, 'learning_rate': 0.0526491937109547, 'optimizer': 'adam'}
config: {}
2022-10-11 04:21:13,156 INFO    Thread-12 :27295 [wandb_init.py:init():492] starting backend
2022-10-11 04:21:13,157 INFO    Thread-12 :27295 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 04:21:13,161 INFO    Thread-12 :27295 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 04:21:13,171 INFO    Thread-12 :27295 [backend.py:ensure_launched():225] started backend process with pid: 27526
2022-10-11 04:21:13,173 INFO    Thread-12 :27295 [wandb_init.py:init():501] backend started and connected
2022-10-11 04:21:13,181 INFO    Thread-12 :27295 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 64, 'dropout': 0.5, 'epochs': 1, 'fc_layer_size': 512, 'learning_rate': 0.0526491937109547, 'optimizer': 'adam'}
2022-10-11 04:21:13,183 INFO    Thread-12 :27295 [wandb_init.py:init():565] updated telemetry
2022-10-11 04:21:13,204 INFO    Thread-12 :27295 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 04:21:14,146 INFO    Thread-12 :27295 [wandb_run.py:_on_init():1759] communicating current version
2022-10-11 04:21:14,184 INFO    Thread-12 :27295 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.13.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-10-11 04:21:14,184 INFO    Thread-12 :27295 [wandb_init.py:init():625] starting run threads in backend
2022-10-11 04:21:16,989 INFO    Thread-12 :27295 [wandb_run.py:_console_start():1733] atexit reg
2022-10-11 04:21:16,990 INFO    Thread-12 :27295 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-10-11 04:21:16,990 INFO    Thread-12 :27295 [wandb_run.py:_redirect():1611] Redirecting console.
2022-10-11 04:21:16,990 ERROR   Thread-12 :27295 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-10-11 04:21:16,991 INFO    Thread-12 :27295 [wandb_init.py:init():664] run started, returning control to user process
2022-10-11 04:21:16,991 INFO    Thread-12 :27295 [wandb_run.py:finish():1539] finishing run vietnguyen/meme_experiments/k4n9z3o0
2022-10-11 04:21:16,991 INFO    Thread-12 :27295 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-10-11 04:21:16,994 INFO    Thread-12 :27295 [wandb_run.py:_restore():1674] restore
2022-10-11 04:21:17,129 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 699
}

2022-10-11 04:21:17,327 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 699
}

2022-10-11 04:21:18,168 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 9455
}

2022-10-11 04:21:18,271 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 699
  total_bytes: 9455
}

2022-10-11 04:21:18,373 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:18,475 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:18,577 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:18,679 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:18,781 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:18,882 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:19,091 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}

2022-10-11 04:21:19,445 INFO    Thread-12 :27295 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 9455
  total_bytes: 9455
}
local_info {
}

2022-10-11 04:21:21,017 INFO    Thread-12 :27295 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-10-11 04:21:21,018 INFO    Thread-12 :27295 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-10-11 04:21:21,019 INFO    Thread-12 :27295 [wandb_run.py:_footer_sync_info():2822] logging synced files
