2022-10-11 03:34:26,649 INFO    Thread-14 :17494 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-10-11 03:34:26,650 INFO    Thread-14 :17494 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-10-11 03:34:26,650 INFO    Thread-14 :17494 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'meme_experiments', 'entity': 'vietnguyen', 'root_dir': '/content/SSLMemes', 'run_id': 'u0zhvbj2', 'sweep_param_path': '/content/SSLMemes/wandb/sweep-9rr6akcl/config-u0zhvbj2.yaml', 'sweep_id': '9rr6akcl'}
2022-10-11 03:34:26,650 INFO    Thread-14 :17494 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program': '/content/SSLMemes/src/train.py'}
2022-10-11 03:34:26,650 INFO    Thread-14 :17494 [wandb_init.py:_log_setup():405] Logging user logs to /content/SSLMemes/wandb/run-20221011_033426-u0zhvbj2/logs/debug.log
2022-10-11 03:34:26,650 INFO    Thread-14 :17494 [wandb_init.py:_log_setup():406] Logging internal logs to /content/SSLMemes/wandb/run-20221011_033426-u0zhvbj2/logs/debug-internal.log
2022-10-11 03:34:26,650 INFO    Thread-14 :17494 [wandb_init.py:init():439] calling init triggers
2022-10-11 03:34:26,650 INFO    Thread-14 :17494 [wandb_init.py:init():443] wandb.init called with sweep_config: {'batch_size': 56, 'dropout': 0, 'epochs': 1, 'hidden_size': 512, 'learning_rate': 0.005867113357574505, 'optimizer': 'adam'}
config: {}
2022-10-11 03:34:26,651 INFO    Thread-14 :17494 [wandb_init.py:init():492] starting backend
2022-10-11 03:34:26,651 INFO    Thread-14 :17494 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-10-11 03:34:26,659 INFO    Thread-14 :17494 [backend.py:ensure_launched():219] starting backend process...
2022-10-11 03:34:26,751 INFO    Thread-14 :17494 [backend.py:ensure_launched():225] started backend process with pid: 18069
2022-10-11 03:34:26,754 INFO    Thread-14 :17494 [wandb_init.py:init():501] backend started and connected
2022-10-11 03:34:26,771 INFO    Thread-14 :17494 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 56, 'dropout': 0, 'epochs': 1, 'hidden_size': 512, 'learning_rate': 0.005867113357574505, 'optimizer': 'adam'}
2022-10-11 03:34:26,779 INFO    Thread-14 :17494 [wandb_init.py:init():565] updated telemetry
2022-10-11 03:34:26,993 INFO    Thread-14 :17494 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-10-11 03:34:57,012 ERROR   Thread-14 :17494 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_init.py", line 597, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 320, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
